### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by MRKDaGods** [voidZiAD/AnghamiRPC#1]
Sleeping for a bit in that while loop is never going to hurt :)

Without sleeping
![image](https://github.com/voidZiAD/AnghamiRPC/assets/25166537/c862e70d-479d-4348-a4cf-864006229446)

With sleeping
![image](https://github.com/voidZiAD/AnghamiRPC/assets/25166537/3f41bb08-4ce7-4959-b419-10052b703b75)

![image](https://github.com/voidZiAD/AnghamiRPC/assets/25166537/237d57c0-2191-4fe6-bfb9-0ae6e1ce2859)

**Comment by simplehima** [comment]
thanks for noticing i will add it  

> Sleeping for a bit in that while loop is never going to hurt :)
> 
> Without sleeping ![image](https://private-user-images.githubusercontent.com/25166537/287243754-c862e70d-479d-4348-a4cf-864006229446.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTY1MDIsIm5iZiI6MTcwMTQ1NjIwMiwicGF0aCI6Ii8yNTE2NjUzNy8yODcyNDM3NTQtYzg2MmU3MGQtNDc5ZC00MzQ4LWE0Y2YtODY0MDA2MjI5NDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE4NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNGY0MjY1ZjdiMTE4OTc0Y2E3OTU4NTVhOTM2MTNkZWQxNTI1ZWQyYmRiZjJlZGVjMjRhNWQ5NjUwMTgwNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJvLhM7ua92eRsME3d7RpU6vXFsQafbx-Y1shBBEX1M)
> 
> With sleeping ![image](https://private-user-images.githubusercontent.com/25166537/287244030-3f41bb08-4ce7-4959-b419-10052b703b75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTY1MDIsIm5iZiI6MTcwMTQ1NjIwMiwicGF0aCI6Ii8yNTE2NjUzNy8yODcyNDQwMzAtM2Y0MWJiMDgtNGNlNy00OTU5LWI0MTktMTAwNTJiNzAzYjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE4NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTJkMmRkZmQwMDhkZjRmNzJmMTJjZWEwYTgzZmEzY2QzNTM2ZDcxNDgwZjc1OGIwMWJmMGIzZDFkYzRlZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IaQNRFAOV2L8JoSjfQ5t77zdHq0QnxlU8B6UXpIlUOM)
> 
> ![image](https://private-user-images.githubusercontent.com/25166537/287244204-237d57c0-2191-4fe6-bfb9-0ae6e1ce2859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTY1MDIsIm5iZiI6MTcwMTQ1NjIwMiwicGF0aCI6Ii8yNTE2NjUzNy8yODcyNDQyMDQtMjM3ZDU3YzAtMjE5MS00ZmU2LWJmYjktMGFlNmUxY2UyODU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE4NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZGE5ZmFiYmFhMDVhYmYyZDkwYzI4MWExMWYzZGI3NzZmZDMxMzkzZDFmNzY4ZjdlMDBjYmNmYzBlMDY1MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F4pUiYz71l9lPWVylWwPHK8_7zqPA5DF_HkO8kk_mM4)

**Comment by voidZiAD** [comment]
👀
