### ISSUE TITLE
Are you Intrested for a GUI App

### ISSUE THREAD

**Issue by simplehima** [voidZiAD/AnghamiRPC#3]
i am interested in building a GUI app to support the RPC instead of a script ?

**Comment by voidZiAD** [comment]
Sure! You can do that if you'd like!
I personally stopped programming so I can't really help with that, but I'm able to push your fixes, improvements and changes to the repo so feel free to do so!

**Comment by simplehima** [comment]
alright i will add it as a branch currently and push back to you i would be pleased if you added me as a contributor

**Comment by voidZiAD** [comment]
Sure thing

**Comment by voidZiAD** [comment]
Let me know when it's done and push it, I will head to sleep now as it's 11PM. 
Will merge once I wake up tomorrow. Have a nice night ✌️

**Comment by simplehima** [comment]
> Let me know when it's done and push it, I will head to sleep now as it's 11PM. Will merge once I wake up tomorrow. Have a nice night ✌️

Check out the [Releases](https://github.com/simplehima/AnghamiRPC/releases) page for pre-built executables. Download the latest release ZIP file, extract, and run `AnghamiRPC.exe`.

**Comment by voidZiAD** [comment]
I've updated the UI. Felt like it wasn't very professional, even though this was a simple app. Thank you for your contributions though. I had time as well so I thought I'd do it just for fun.
